const PREPROCESSOR_COPY = {
  zh: {
    title: "字幕预处理",
    description: "先清理 SDH 提示，再按选项合并字幕内容。处理完成后可以保存到本地。",
    optionsTitle: "预处理选项",
    removeBracketedSdhWithoutKeywordCheck: "括号匹配即移除，不判断关键词",
    removeBracketedSdhWithoutKeywordCheckHint: "默认会结合中英日韩常见 SDH 关键词判断；勾选后只要命中括号形式就会移除，更激进。",
    removeRoundBracketSdh: "移除圆括号 SDH",
    removeRoundBracketSdhHint: "包含 () 和 （），常见于欧美、日韩字幕： (sighs)、(whispering)、（叹气）、（旁白）",
    removeSquareBracketSdh: "移除方括号 SDH",
    removeSquareBracketSdhHint: "包含 [] 和 ［］，常见于平台字幕： [MUSIC]、[door opens]、[笑]、[拍手]",
    removeCornerBracketSdh: "移除【】类 SDH",
    removeCornerBracketSdhHint: "常见于中文、日系熟肉或电视字幕： 【脚步声】、【旁白】、【电话铃声】",
    removeHesitationEllipses: "清理中英文犹豫停顿",
    removeHesitationEllipsesHint: "仅处理 SRT/VTT。会清理常见台词里的重复词口吃，以及犹豫词后的省略号或逗号，例如 我……我、I... I、呃……、Uh...、嗯，、Well,",
    removeInlineFormattingTags: "移除内联格式标记",
    removeInlineFormattingTagsHint: "用于清理 SRT/VTT 中的 <i>、<b>、<u>、<font> 以及 {\\an8} 这类内联样式标记",
    removeSpeakerLabels: "移除说话人标签",
    removeSpeakerLabelsHint: "例如 SOME ONE SAY: hello、JOHN: hello",
    removeUppercaseSdh: "移除全大写音效提示",
    removeUppercaseSdhHint: "例如 MUSIC、DOOR OPENS、LOUD BREATHING",
    removeRepeatedQuoteMarks: "移除跨字幕块重复引号",
    removeRepeatedQuoteMarksHint: "仅处理 SRT/VTT。连续多个字幕块都以同一种外层引号开头时，移除重复开头引号和对应结尾引号；不会处理 You're、'90s、'cause。",
    mergeSameTimestamps: "合并相同时间戳的字幕",
    mergeSameTimestampsHint: "同一时间范围出现多条字幕时，用空格合并成一条",
    mergeLinesWithinCue: "合并同一字幕块内多行",
    mergeLinesWithinCueHint: "同一时间戳里的多行内容会合并到同一行",
    resultTitle: "预处理结果",
    noProcessedText: "请先完成字幕预处理",
    processedStats: (output: number, original: number, removed: number, merged: number) => `输出 ${output}/${original} 条，移除 ${removed} 条，合并 ${merged} 处`,
    logTitle: "SDH 清理日志",
    noLogs: "这次处理没有移除任何 SDH 提示。",
    roundBracketLog: "圆括号 SDH",
    squareBracketLog: "方括号 SDH",
    cornerBracketLog: "【】类 SDH",
    uppercaseLog: "全大写音效提示",
    speakerLabelLog: "说话人标签",
  },
  en: {
    title: "Subtitle Preprocess",
    description: "Clean SDH cues before translation, then merge subtitle content based on your options. You can save the result locally after processing.",
    optionsTitle: "Preprocess Options",
    removeBracketedSdhWithoutKeywordCheck: "Remove bracketed text without keyword checks",
    removeBracketedSdhWithoutKeywordCheckHint: "By default bracketed text is checked against common SDH keywords. Enable this to remove any matched bracketed text more aggressively.",
    removeRoundBracketSdh: "Remove round-bracket SDH",
    removeRoundBracketSdhHint: "Includes () and （）. Common in Western and East Asian subtitles: (sighs), (whispering), （旁白）",
    removeSquareBracketSdh: "Remove square-bracket SDH",
    removeSquareBracketSdhHint: "Includes [] and ［］. Common in streaming/platform captions: [MUSIC], [door opens], [笑]",
    removeCornerBracketSdh: "Remove 【】 SDH",
    removeCornerBracketSdhHint: "Common in Chinese and Japanese fan/TV subtitles: 【脚步声】, 【旁白】, 【电话铃声】",
    removeHesitationEllipses: "Clean hesitation pauses",
    removeHesitationEllipsesHint: "Only affects SRT/VTT. Cleans repeated-word stammers plus ellipses or commas after common hesitation fillers, such as 我……我, I... I, 呃……, Uh..., 嗯，, and Well,",
    removeInlineFormattingTags: "Remove inline formatting tags",
    removeInlineFormattingTagsHint: "Cleans SRT/VTT tags such as <i>, <b>, <u>, <font>, and inline markers like {\\an8}",
    removeSpeakerLabels: "Remove speaker labels",
    removeSpeakerLabelsHint: "Examples: SOME ONE SAY: hello, JOHN: hello",
    removeUppercaseSdh: "Remove uppercase sound cues",
    removeUppercaseSdhHint: "Examples: MUSIC, DOOR OPENS, LOUD BREATHING",
    removeRepeatedQuoteMarks: "Remove repeated quote marks across cues",
    removeRepeatedQuoteMarksHint: "Only affects SRT/VTT. When consecutive cues start with the same outer quote mark, removes the repeated opening marks and matching closing marks; keeps You're, '90s, and 'cause.",
    mergeSameTimestamps: "Merge subtitles with identical timestamps",
    mergeSameTimestampsHint: "Combine subtitles in the same time range into one line with spaces",
    mergeLinesWithinCue: "Merge multi-line subtitles inside one cue",
    mergeLinesWithinCueHint: "Join multiple lines inside the same subtitle cue with spaces",
    resultTitle: "Preprocessed Result",
    noProcessedText: "Process the subtitle content first",
    processedStats: (output: number, original: number, removed: number, merged: number) => `Kept ${output}/${original} cues, removed ${removed}, merged ${merged}`,
    logTitle: "SDH Cleanup Log",
    noLogs: "No SDH cues were removed in this run.",
    roundBracketLog: "Round-bracket SDH",
    squareBracketLog: "Square-bracket SDH",
    cornerBracketLog: "【】 SDH",
    uppercaseLog: "Uppercase sound cue",
    speakerLabelLog: "Speaker label",
  },
} as const;

const COMPOSER_COPY = {
  zh: {
    title: "双语字幕合成",
    description: "上传原文字幕和译文字幕，以译文时间轴为基准自动合成双语字幕。支持导出 SRT 和 ASS，并记录未匹配的字幕。",
    originalTitle: "原文字幕",
    translatedTitle: "译文字幕",
    optionsTitle: "合成选项",
    outputFormat: "输出格式",
    assTemplateMode: "ASS 模板",
    hdrTemplate: "HDR 模板",
    sdrTemplate: "SDR 模板",
    templateEditor: "ASS 模板编辑器",
    templateHint: "Chs 用于译文样式，Eng 用于原文样式，Tip 已预留。",
    resetTemplate: "恢复初始模板",
    saveTemplate: "保存模板",
    templateReset: "模板已恢复为初始值",
    templateSaved: "模板已保存",
    startCompose: "开始合成",
    resultTitle: "合成结果",
    logTitle: "未匹配日志",
    noLogs: "本次合成没有未匹配字幕。",
    noSourceText: "请上传或粘贴原文字幕和译文字幕",
    unsupportedSubtitle: "当前仅支持 SRT、VTT、ASS 参与双语合成",
    composedSuccess: "双语字幕已生成",
    translatedUnmatched: "译文未匹配",
    originalUnmatched: "原文未匹配",
    saveResult: "导出双语字幕",
    resultSummary: (matched: number, translatedOnly: number, originalOnly: number, total: number) =>
      `已匹配 ${matched} 条，译文未匹配 ${translatedOnly} 条，原文未匹配 ${originalOnly} 条，输出共 ${total} 条`,
  },
  en: {
    title: "Bilingual Subtitle Composer",
    description: "Upload original and translated subtitles, then compose bilingual subtitles using the translated timeline as the base. Export as SRT or ASS and review unmatched cues below.",
    originalTitle: "Original Subtitle",
    translatedTitle: "Translated Subtitle",
    optionsTitle: "Compose Options",
    outputFormat: "Output Format",
    assTemplateMode: "ASS Template",
    hdrTemplate: "HDR Template",
    sdrTemplate: "SDR Template",
    templateEditor: "ASS Template Editor",
    templateHint: "Chs is used for translated lines, Eng for original lines, and Tip is reserved.",
    resetTemplate: "Reset Template",
    saveTemplate: "Save Template",
    templateReset: "Template reset to default",
    templateSaved: "Template saved",
    startCompose: "Compose Subtitle",
    resultTitle: "Composed Result",
    logTitle: "Unmatched Log",
    noLogs: "No unmatched subtitle cues in this run.",
    noSourceText: "Please upload or paste both original and translated subtitles",
    unsupportedSubtitle: "Only SRT, VTT, and ASS are supported for bilingual composition",
    composedSuccess: "Bilingual subtitle generated",
    translatedUnmatched: "Translated unmatched",
    originalUnmatched: "Original unmatched",
    saveResult: "Export Bilingual Subtitle",
    resultSummary: (matched: number, translatedOnly: number, originalOnly: number, total: number) =>
      `Matched ${matched}, translated-only ${translatedOnly}, original-only ${originalOnly}, output ${total}`,
  },
} as const;

const WORKSPACE_COPY = {
  zh: {
    modeLabel: "字幕工具模式",
    preprocess: "字幕预处理",
    translate: "字幕翻译",
    bilingual: "双语合成",
  },
  en: {
    modeLabel: "Subtitle tool mode",
    preprocess: "Subtitle Preprocessor",
    translate: "Subtitle Translation",
    bilingual: "Bilingual Composer",
  },
} as const;

export const getSubtitleToolsCopy = (locale: string) => {
  const language = locale === "zh" || locale === "zh-hant" ? "zh" : "en";
  return {
    workspace: WORKSPACE_COPY[language],
    preprocessor: PREPROCESSOR_COPY[language],
    composer: COMPOSER_COPY[language],
  };
};

