import assert from "node:assert/strict";
import test from "node:test";
import {
  detectSubtitleFormat,
  formatMsToAss,
  formatMsToSrt,
  parseTimelineSubtitle,
} from "../../src/features/subtitle-tools/lib/subtitleParsing";

test("detects supported local subtitle formats", () => {
  assert.equal(detectSubtitleFormat("1\n00:00:01,000 --> 00:00:02,000\nHi"), "srt");
  assert.equal(detectSubtitleFormat("WEBVTT\n\n00:01.000 --> 00:02.000\nHi"), "vtt");
  assert.equal(
    detectSubtitleFormat("[Script Info]\n[Events]\nDialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hi"),
    "ass",
  );
  assert.equal(detectSubtitleFormat("[00:01.00]Hi"), "lrc");
  assert.equal(detectSubtitleFormat("plain text"), null);
});

test("parses timed SRT, VTT, and ASS cues without formatting tags", () => {
  const srt = parseTimelineSubtitle("1\n00:00:01,000 --> 00:00:02,250\n<i>Hello</i>\nworld");
  assert.equal(srt?.fileType, "srt");
  assert.deepEqual(srt?.cues, [{ startMs: 1000, endMs: 2250, text: "Hello world" }]);

  const vtt = parseTimelineSubtitle("WEBVTT\n\n00:01.000 --> 00:02.000 align:start\n<c.blue>Hello</c>");
  assert.deepEqual(vtt?.cues, [{ startMs: 1000, endMs: 2000, text: "Hello" }]);

  const ass = parseTimelineSubtitle(
    "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.20,0:00:02.50,Default,,0,0,0,,{\\i1}Hello\\Nworld",
  );
  assert.deepEqual(ass?.cues, [{ startMs: 1200, endMs: 2500, text: "Hello world" }]);
});

test("ignores WebVTT metadata blocks", () => {
  const parsed = parseTimelineSubtitle(
    "WEBVTT\n\nNOTE generated by test\n00:10.000 --> 00:11.000\nnot a cue\n\nSTYLE\n::cue { color: lime; }\n\n00:01.000 --> 00:02.000\nHello",
  );

  assert.deepEqual(parsed?.cues, [{ startMs: 1000, endMs: 2000, text: "Hello" }]);
});

test("formats millisecond values for SRT and ASS", () => {
  assert.equal(formatMsToSrt(3723456), "01:02:03,456");
  assert.equal(formatMsToAss(3723456), "1:02:03.45");
});

test("does not treat LRC as an end-timed composition format", () => {
  assert.equal(parseTimelineSubtitle("[00:01.00]Hello"), null);
});
